### ISSUE TITLE
Syntex versions and crate versions

### ISSUE THREAD

**Issue by slapresta** [slapresta/rust-dotenv#35]
We've had a few pull requests open for bumping the syntex version (#27, #29, #30, #34) and I'd like to find a longer-term solution to this issue. Thoughts?

Also, I've been aiming to keep the crate versions synced between `dotenv`, `dotenv_macros` and `dotenv_codegen`. This is probably not necessary or a good idea? Again, thoughts welcome.

**Comment by sgrif** [comment]
> Also, I've been aiming to keep the crate versions synced between dotenv, dotenv_macros and dotenv_codegen. This is probably not necessary or a good idea?

If the actual requirements for syntex versions haven't changed, I think it can be a teeny version bump instead of a minor one. What I've been doing for Diesel for these cases is: Diesel CLI had a change that I wanted to release by itself. I bumped Diesel CLI to 0.5.1, but didn't release new versions of anything else. If in the next release Diesel proper has changes, I'll bump it to 0.5.2 and there just won't be a 0.5.1. Mainly just considering what people likely have in their Cargo.toml files, since that's all the version number really matters for.

**Comment by indiv0** [comment]
Would it be possible to bump the syntex version to 0.30.0 so that I can use this package with serde_codegen?

@slapresta If so, should I submit a PR bumping the versions or do you want to consider the longer term solution now?

**Comment by sgrif** [comment]
As an aside, the end may be in sight here, as there is now an RFC for stabilizing procedural macros. https://github.com/rust-lang/rfcs/pull/1566

**Comment by sgrif** [comment]
Closing, as I'm now able to handle this without putting additional effort on others, and am willing to keep on top of it. Until libmacro is ready (which means that we're close to stable anyway), I don't foresee anything occurring that would require more than a patch level version bump, and the versions don't need to be in sync beyond that since the version used by dotenv_codegen is independent of usage in the app if any.
